name: ci
on: [push, pull_request]
jobs:
  test_freebsd:
    name: Tests/FreeBSD test suite
#    needs: [ lint ]
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: macos-10.15 , features: "dist-client,dist-server" } ## GHA MacOS-11.0 VM won't have VirtualBox; refs: <https://github.com/actions/virtual-environments/issues/4060> , <https://github.com/actions/virtual-environments/pull/4010>
    env:
      mem: 2048
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Prepare, build and test
      uses: vmactions/freebsd-vm@v0.1.6
      with:
        usesh: true
        prepare: pkg install -y ca_root_nss gmake gtar pot
        run: |
          ## Prepare, build, and test
          # implementation modelled after ref: <https://github.com/rust-lang/rustup/pull/2783>
          # and https://github.com/uutils/coreutils/commit/86c610a84b8b6c
          # * NOTE: All steps need to be run in this block, otherwise, we are operating back on the mac host
          set -e
          #
          TEST_USER=tester
          TEST_USER_HOME=/tmp/tester
          REPO_NAME=${GITHUB_WORKSPACE##*/}
          WORKSPACE_PARENT="/Users/runner/work/${REPO_NAME}"
          WORKSPACE="${WORKSPACE_PARENT}/${REPO_NAME}"
          OS_VERSION="$(freebsd-version | awk -F- '{print $1}')"
          #
          mkdir -p "$TEST_USER_HOME"
          pw adduser -n "$TEST_USER" -d "$TEST_USER_HOME" -c "Tester" -h -
          chown -R "$TEST_USER":"$TEST_USER" "$TEST_USER_HOME" "/$WORKSPACE_PARENT"/
          whoami
          #
          ## Create ZFS pool and configure pot
          dd if=/dev/zero of=/zfs1 bs=1 count=1 seek=2G
          zdev=$(mdconfig -a -t vnode -S 4096 -f /zfs1)
          zpool create -f potpool "$zdev"
          sysrc -f /usr/local/etc/pot/pot.conf POT_ZFS_ROOT=potpool/pot
          sysrc -f /usr/local/etc/pot/pot.conf POT_EXTIF=en0
          ifconfig
          pot init
          pot create -p sccache-template -N alias -i "lo0|127.0.0.2" -t single -b "$OS_VERSION"
          pot set-cmd -p sccache-template -c /usr/bin/true
          pot set-attr -p sccache-template -A no-rc-script -V YES
          pot snapshot -p sccache-template
          #
          su -l "$TEST_USER"
          set -e
          whoami
          fetch -o /tmp/rustup.sh https://sh.rustup.rs
          sh /tmp/rustup.sh -y --profile=minimal
          . $HOME/.cargo/env
          ## Info
          # environment
          echo "## environment"
          env | sort
          # tooling info
          echo "## tooling info"
          cargo -V
          rustc -V
          #
          cd "${WORKSPACE}"
          FAULT=0
          cargo build --features "${{ matrix.job.features }}" || FAULT=1
          cargo test --features "${{ matrix.job.features }}" || FAULT=1
          if [ "$FAULT" -eq 0 ]; then
            # save build time by avoiding "cargo install"
            cp -a target/debug/sccache target/debug/sccache-dist $HOME/.cargo/bin/.
          fi
          # Clean to avoid to rsync back the files
          cargo clean
          if [ $FAULT -ne 0 ]; then exit 1; fi

          # run some tests
          echo "Run some more tests here"
          EOF

